### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-LC_wrapper#4]
The exception `TypeError: write() argument must be str, not bytes` occurred on Python3.

The details are as follows...

```
[IPKernelApp] ERROR | a exception caught in execute_interactive
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 575, in execute_request
    super(PythonKernelBuffered, self).execute_request(stream, ident, parent)
  File "/opt/conda/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 601, in do_execute
    timeout=None, output_hook=output_hook, stdin_hook=stdin_hook, reply_hook=reply_hook)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 847, in execute_interactive
    return reply_hook(msg_id, timeout=timeout)
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 534, in reply_hook_summarize
    self.close_files()
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 399, in close_files
    self.log_buff_flush()
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 332, in log_buff_flush
    self.file_full_path = self.write_log_file(self.log_path, self.file_full_path, u''.join(self.summarize_log_buff))
  File "/opt/conda/lib/python3.5/site-packages/lc_wrapper.py", line 117, in write_log_file
    self.log_file_object.write(msg.encode('utf-8'))
TypeError: write() argument must be str, not bytes

```

**Comment by yacchin1205** [comment]
I seems that the code attempts to write bytes to text stream...

The stream has been opened at https://github.com/NII-cloud-operation/Jupyter-LC_wrapper/blob/master/lc_wrapper.py#L122, with mode "a" ... in text mode(because without "b").
But, in python3, the `unicode.encode()` like https://github.com/NII-cloud-operation/Jupyter-LC_wrapper/blob/master/lc_wrapper.py#L117 returns byte array...

I assume that there are two options...

1. open log_file_object in binary mode and write output in bytes
2. open log_file_object in text mode(maybe... using `io.open` with encoding) and write output in unicode

@shingo78 Which is the better option to support both Python2 and 3? I'm going to fix this...

**Comment by shingo78** [comment]
I think that the 2nd option is better because the log file is text file, not binary file.

And, use `io.open` with `encoding` parameter, because in Python2 `open` doesn't accept encoding and raises a UnicodeEncodeError if unicode object includes non-ascii character.

**Comment by yacchin1205** [comment]
Thanks @shingo78 ! I'll make PR 😄
