### ISSUE TITLE
input() is not working

### ISSUE THREAD

**Issue by yacchin1205** [NII-cloud-operation/Jupyter-LC_wrapper#65]
When the input() function is executed in a code cell, the input field is not displayed.

Code cell:
```
s = input()
s
```

Debug logs:
```
[IPKernelApp] Received iopub message: {'header': {'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_15', 'msg_type': 'status', 'username': 'username', 'session': '7f8a00fc-936bc71c87c31a881704c41e', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 385432, tzinfo=tzlocal()), 'version': '5.3'}, 'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_15', 'msg_type': 'status', 'parent_header': {'msg_id': '820c7b63-ec7830f46012cfbd037ee34a_67_5', 'msg_type': 'execute_request', 'username': 'username', 'session': '820c7b63-ec7830f46012cfbd037ee34a', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 353544, tzinfo=tzlocal()), 'version': '5.3'}, 'metadata': {}, 'content': {'execution_state': 'busy'}, 'buffers': []}
[IPKernelApp] parent_header: {'date': datetime.datetime(2022, 3, 24, 2, 33, 49, 848000, tzinfo=tzlocal()), 'msg_id': '7a61746514b74804b5603fa741a96689', 'username': 'username', 'session': '1a2c058f155f4cfe8654a0202416ae40', 'msg_type': 'execute_request', 'version': '5.2'}
[IPKernelApp] Received iopub message: {'header': {'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_16', 'msg_type': 'execute_input', 'username': 'username', 'session': '7f8a00fc-936bc71c87c31a881704c41e', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 390266, tzinfo=tzlocal()), 'version': '5.3'}, 'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_16', 'msg_type': 'execute_input', 'parent_header': {'msg_id': '820c7b63-ec7830f46012cfbd037ee34a_67_5', 'msg_type': 'execute_request', 'username': 'username', 'session': '820c7b63-ec7830f46012cfbd037ee34a', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 353544, tzinfo=tzlocal()), 'version': '5.3'}, 'metadata': {}, 'content': {'code': 's = input()\ns', 'execution_count': 1}, 'buffers': []}
[IPKernelApp] parent_header: {'date': datetime.datetime(2022, 3, 24, 2, 33, 49, 848000, tzinfo=tzlocal()), 'msg_id': '7a61746514b74804b5603fa741a96689', 'username': 'username', 'session': '1a2c058f155f4cfe8654a0202416ae40', 'msg_type': 'execute_request', 'version': '5.2'}
[IPKernelApp] Received stdin message: {'header': {'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_17', 'msg_type': 'input_request', 'username': 'username', 'session': '7f8a00fc-936bc71c87c31a881704c41e', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 688040, tzinfo=tzlocal()), 'version': '5.3'}, 'msg_id': '7f8a00fc-936bc71c87c31a881704c41e_83_17', 'msg_type': 'input_request', 'parent_header': {'msg_id': '820c7b63-ec7830f46012cfbd037ee34a_67_5', 'msg_type': 'execute_request', 'username': 'username', 'session': '820c7b63-ec7830f46012cfbd037ee34a', 'date': datetime.datetime(2022, 3, 24, 2, 33, 50, 353544, tzinfo=tzlocal()), 'version': '5.3'}, 'metadata': {}, 'content': {'prompt': '', 'password': False}, 'buffers': []}
[IPKernelApp] parent_header: {'date': datetime.datetime(2022, 3, 24, 2, 33, 49, 848000, tzinfo=tzlocal()), 'msg_id': '7a61746514b74804b5603fa741a96689', 'username': 'username', 'session': '1a2c058f155f4cfe8654a0202416ae40', 'msg_type': 'execute_request', 'version': '5.2'}
[IPKernelApp] ERROR | Frame 0 ({'shell': [b'1a2c058f155f4cfe865...) does not support the buffer interface.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/zmq/sugar/socket.py", line 582, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/lc_wrapper/kernel.py", line 124, in run
    self.session.send(self.stream,
  File "/opt/conda/lib/python3.9/site-packages/jupyter_client/session.py", line 853, in send
    stream.send_multipart(to_send, copy=copy)
  File "/opt/conda/lib/python3.9/site-packages/zmq/sugar/socket.py", line 587, in send_multipart
    raise TypeError(
TypeError: Frame 0 ({'shell': [b'1a2c058f155f4cfe865...) does not support the buffer interface.

```

**Comment by yacchin1205** [comment]
I found that the _parent_ident that ipykernel has used to be bytes, but in the latest version it is now dict, so it was failing.

https://github.com/NII-cloud-operation/Jupyter-LC_wrapper/blob/master/lc_wrapper/kernel.py#L120
