### ISSUE TITLE
Jupyter-LC_wrapperのインストールに失敗する

### ISSUE THREAD

**Issue by ivis-mizuguchi** [NII-cloud-operation/Jupyter-LC_wrapper#69]
Jupyter-LC_wrapperの利用手順について質問がございます。
Jupyter環境上でJupyterNotebook実行のログ出力にJupyter-LC_wrapperを活用したいと考えておりますが、インストールで以下の事象が発生しております。恐れ入りますが、助言いただけますでしょうか。
 
◇実行手順
Jupyter-LC_wrapperのREADME.mdに従い、jupyter環境のコンテナで以下のモジュールのpipインストールと有効化を実施した。
・lc_wrapper
・Jupyter-LC_nblineage
・Jupyter-multi_outputs
◇発生した事象
Jupyter-LC_nblineageのインストール後にnbextensionが動かなくなってしまい、「which jupyter-nbextension」でパスも表示されない状況になる。
◇実行コード
jupyter nblineage quick-setup
◇出力
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nblineage", line 5, in <module>
    from nblineage.extensionapp import main
  File "/opt/conda/lib/python3.9/site-packages/nblineage/__init__.py", line 1, in <module>
    from notebook.base.handlers import IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
 
ちなみに、以下のようなログをJupyterNotebookのセル単位に出力したいと考えております。
・実行対象のJupyterNotebookファイルパス
・実行セルのID
・セルの実行開始日時
・セルの実行終了日時
・セルの結果
・エラー詳細
・実行ユーザ名
・フォーム入力を用意したコードセルに対しての入力値
 
以上、お手数をおかけしますがよろしくお願いいたします。

**Comment by yacchin1205** [comment]
エラーから推測するに、notebookモジュールの解決に失敗しているようです。ここ最近Notebook 7が出たので、その関係かもしれません。(そのため、今後我々のモジュールも大きく変更が入る予定です。)

依存関係を自己解決できない場合、全部入りイメージを使っていただくのが早いかもしれません。よろしくお願いいたします。 https://hub.docker.com/r/niicloudoperation/notebook

**Comment by ivis-mizuguchi** [comment]
ご回答いただきありがとうございます。
事象について承知いたしました。全部入りイメージを試してみます。
